apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: pvtest
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 3
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver
          image: pk-hbr-hj-801.hj.vm/harborpj1/example/webserver:latest
          ports:
            - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiengine
  namespace: pvtest
spec:
  selector:
    matchLabels:
      app: apiengine
  replicas: 1
  template:
    metadata:
      labels:
        app: apiengine
    spec:
      containers:
        - name: apiengine
          image: pk-hbr-hj-801.hj.vm/harborpj1/example/apiengine:latest

---
apiVersion: v1
kind: Service
metadata:
  name: webserver-svc
  namespace: pvtest
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: webserver

---
apiVersion: v1
kind: Service
metadata:
  name: apiengine-svc
  namespace: pvtest
spec:
  type: ClusterIP
  ports:
    - port: 8081
  selector:
    app: apiengine

