apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  namespace: pvtest
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  vsphereVolume:
    volumePath: "/vmfs/volumes/VxRail-Virtual-SAN-Datastore-00fad154-42eb-4c54-b47f-0cce5312f867/kubevols/pv"
    fsType: ext4
